name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
        source-url: https://api.nuget.org/v3/index.json
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack --no-build --configuration Release Garbacik.NetCore.Utilities.Restful/Garbacik.NetCore.Utilities.Restful.csproj --output .
    - name: Push Github Packages
      run: dotnet nuget push *.nupkg --no-symbols --skip-duplicate --source https://nuget.pkg.github.com/pawel90g/ --api-key ${{ secrets.PACKAGES_TOKEN }}
